### ISSUE TITLE
resource() und lang() nicht definiert?

### ISSUE THREAD

**Issue by kevingruesser** [fokuscms/blackhound#1]
Hi,

wenn ich alles über composer auf den Server geladen habe wird leider eine leere Seite angezeigt.
Der HTML Code wir nur bis zur ersten PHP Anweisung ausgegeben (Bild 1).

Er hängt also hier an der ausgabe "resource()".
Wenn diese entfernt wird bleibt er an der ausgabe "lang();" hängen.

Ich finde aber auch keine Datei in der die beiden ausgaben definiert werden.

Habe ich was vergessen?

![unbenannt](https://cloud.githubusercontent.com/assets/95678/9914729/85f6d0e8-5cb3-11e5-809b-1020d05a84c5.PNG)

**Comment by rathesDot** [comment]
Ich habe das Problem nicht. Hat die Installation bei dir vollständig geklappt? Die Funktionen `resource()` und `trans()` findest du unter `fokuscms\components\View\Engine\helpers.php`

**Comment by kevingruesser** [comment]
Ok Problem gefunden. Git war bei mir nicht installiert und ich habe die Fehlermeldung vom Composer übersehen. Ist es richtig das Git vorhanden sein muss um Blackhound über Composer zu installieren?

**Comment by rathesDot** [comment]
Hi. Aktuell ist es noch notwendig. Ich habe fokuscms/components noch nicht bei packagist eingestellt, da die ganzen Konfigurations-Dateien noch fehlen. Wird zur ersten Stable nachgeholt. (Dann sind alle unnötigen Komponenten ja weg.)
